# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
pod 'RestKit', '~> 0.20.0'


pod 'Firebase/Auth'
pod 'Firebase/Database'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

end
